version: "3.9"
services:
  nats:
    image: nats:latest
    container_name: nats_server
    ports:
      - "4222:4222" # Client connections
      - "8222:8222" # HTTP management

volumes:
  nats_data:
    driver: local

