version: '3.8'
services:
  arangodb:
    image: arangodb/arangodb:3.11.8
    environment:
      - ARANGO_ROOT_PASSWORD=rootpassword
      - "8529:8529"
    ports:
      - "8529:8529"
    network_mode: host
    volumes:
      - arangodb_data:/var/lib/arangodb3
    restart: always


volumes:
  arangodb_data:
