[tool.poetry]
name = "arangodb"
version = "0.1.0"
description = ""
authors = ["rcastillo <tepuybits@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
python-arango = "^7.9.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
